const MIN_MONEY_COUNT = 5000;
const DEFAULT_MONEY_COUNT = 100000;
const MAX_MONEY_COUNT = 1000000;
const MONEY_COUNT_STEP = 5000;

const PREVIOUS_MONEY_COUNT_PERCENTAGE = 1.17214286;

export default {
    MIN_MONEY_COUNT,
    DEFAULT_MONEY_COUNT,
    MAX_MONEY_COUNT,
    MONEY_COUNT_STEP,
    PREVIOUS_MONEY_COUNT_PERCENTAGE
};
